support python 3.12
healthjoy/async-firebase pull request #64
Opened 2023-10-01 22:44 UTC by TomerBin

2023-10-02 06:58 UTC, akalex requested changes

2023-10-02 06:58 UTC, akalex commented on pyproject.toml
> +version = "3.2.1"
First of all, thank you for contributing to the project. 
As this is not a bugfix, could you please increment the MINOR digit?

2023-10-02 07:02 UTC, akalex commented
I believe you have to use `actions/setup-python@v4` to enable Python 3.12 support.

2023-10-02 07:54 UTC, akalex commented
Okay, let's merge this one, and then I will fix CI/CD so as not to bother you with that stuff. @TomerBin, Are you good with that?

2023-10-02 07:56 UTC, hxtomer commented
> Okay, let's merge this one, and then I will fix CI/CD to avoid bothering you with that stuff. @TomerBin, Are you good with that?

I've added `allow-prereleases: true` to the CI, maybe it'll work? I prefer to let the unit test run in the CI since i haven't run them locally.

2023-10-02 08:09 UTC, akalex commented
> > Okay, let's merge this one, and then I will fix CI/CD to avoid bothering you with that stuff. @TomerBin, Are you good with that?
> 
> I've added `allow-prereleases: true` to the CI, maybe it'll work? I prefer to let the unit test run in the CI since i haven't run them locally.

Okay, that sounds reasonable.

2023-10-02 12:52 UTC, TomerBin commented
@akalex Is it possible to grant me permissions to run the 3.12 action so I can test it effectively? Thank you

2023-10-03 09:30 UTC, akalex commented
> @akalex Is it possible to grant me permissions to run the 3.12 action so I can test it effectively? Thank you

Hey @TomerBin, sorry for the delay. I adjusted the configuration. You should now be able to Run GitHub actions.

2023-10-03 09:33 UTC, akalex approved these changes
LGTM

2023-10-03 11:53 UTC, merged